### ISSUE TITLE
Error in initial import

### ISSUE THREAD

**Issue by orenpapers** [ypeleg/HungaBunga#7]
Hi,
I downloaded and put the package in site-packages.
When importing, I get the error:

```

    from regression import HungaBungaRegressor
ModuleNotFoundError: No module named 'regression'
```

**Comment by JanaMi99** [comment]
@oren1k Hi, I had the same issue. Just replace `from regression import HungaBungaRegressor` with `from .regression import HungaBungaRegressor`  in ` __init__.py`. Do the same for all local file imports (classification in `__init__.py`,  core and params in `classification.py` and `regression.py`)

**Comment by danpol** [comment]
PR #8 should resolve the issue :)

**Comment by henaraihan** [comment]
I was getting the same error. Using the above solution, it worked fine but now I am getting another error:
      5 
C:\Users\.....\lib\site-packages\hunga_bunga\__init__.py in <module>()
      4 from multiprocessing import cpu_count
      5 from sklearn.base import BaseEstimator
----> 6 from regression import HungaBungaRegressor
      7 from classification import HungaBungaClassifier
      8 
C:\Users\......\site-packages\hunga_bunga\regression.py in <module>()
     20 
     21 
---> 22 from .core import *
     23 from .params import *
     24 
SystemError: Parent module '' not loaded, cannot perform relative import

**Comment by danpol** [comment]
I think you should remove pip version (`pip uninstall hunga-bunga`) and install the package again from source (`python setup.py install`).

**Comment by alxgal** [comment]
Hi,
I pulled PR#8 and manually installed hunga_bunga via python setup.py install as described.
However, I still get the ModuleNotFoundError: No module named 'hunga_bunga'
I tried to pip install hunga-bunga again and got the message that the requirements are already satisfied for hunga-bunga.
I now have the file "hunga_bunga-0.1-py3.7.egg" in my python site-packages directory.
Any ideas on how to solve this?
Thanks in advance!

**Comment by danpol** [comment]
Ok, I played with this repo a bit—it contains an **enormous** amount of bugs. I'll close PR#8 not to give hope that it solves all problems :)

**Comment by AbdullahKeteldijk** [comment]
You should change the line to:

`from hunga_bunga.regression import HungaBungaRegressor`

You should repeat that multiple times for all occurrences of that error and you should probably also `pip install tabulate`.

**Comment by kennedykwangari** [comment]
Tried all the options explained above but still facing the same error while importing.


    from regression import HungaBungaRegressor
ModuleNotFoundError: No module named 'regression'

**Comment by smaxwell953** [comment]
I'm in the same boat as kennedykwangari. I too still get "No module named regression".
